language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - make install

script:
  - make build
  - CI=true make test/ci
  - make test/pretty

notifications:
  email: false
