language: node_js

node_js:
  - "10"

cache:
  npm: true
  directories:
    - node_modules

install:
  - make install

script:
  - make build
  - CI=true make test/ci
  - make test/pretty

notifications:
  email: false
