// flow-typed signature: 867f5a61c740563a02bbbd292d7cdabe
// flow-typed version: <<STUB>>/dotenv-flow_v0.2.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-flow/lib/dotenv-flow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-flow/lib/dotenv-flow.js' {
  declare module.exports: $Exports<'dotenv-flow/lib/dotenv-flow'>;
}
