// flow-typed signature: 28ea0b8cd99316194ef5022fe100d73f
// flow-typed version: <<STUB>>/dotenv-flow_v0.4.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-flow/config' {
  declare module.exports: any;
}

declare module 'dotenv-flow/lib/cli-options' {
  declare module.exports: any;
}

declare module 'dotenv-flow/lib/dotenv-flow' {
  declare module.exports: any;
}

declare module 'dotenv-flow/lib/env-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-flow/config.js' {
  declare module.exports: $Exports<'dotenv-flow/config'>;
}
declare module 'dotenv-flow/lib/cli-options.js' {
  declare module.exports: $Exports<'dotenv-flow/lib/cli-options'>;
}
declare module 'dotenv-flow/lib/dotenv-flow.js' {
  declare module.exports: $Exports<'dotenv-flow/lib/dotenv-flow'>;
}
declare module 'dotenv-flow/lib/env-options.js' {
  declare module.exports: $Exports<'dotenv-flow/lib/env-options'>;
}
