// flow-typed signature: 2c290cd580934f9ae27945373c5005dd
// flow-typed version: <<STUB>>/html-loader_v1.3.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'html-loader/dist/HtmlSourceError' {
  declare module.exports: any;
}

declare module 'html-loader/dist' {
  declare module.exports: any;
}

declare module 'html-loader/dist/plugins' {
  declare module.exports: any;
}

declare module 'html-loader/dist/plugins/minimizer-plugin' {
  declare module.exports: any;
}

declare module 'html-loader/dist/plugins/source-plugin' {
  declare module.exports: any;
}

declare module 'html-loader/dist/runtime/getUrl' {
  declare module.exports: any;
}

declare module 'html-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-loader/dist/cjs.js' {
  declare module.exports: $Exports<'html-loader/dist/cjs'>;
}
declare module 'html-loader/dist/HtmlSourceError.js' {
  declare module.exports: $Exports<'html-loader/dist/HtmlSourceError'>;
}
declare module 'html-loader/dist/index' {
  declare module.exports: $Exports<'html-loader/dist'>;
}
declare module 'html-loader/dist/index.js' {
  declare module.exports: $Exports<'html-loader/dist'>;
}
declare module 'html-loader/dist/plugins/index' {
  declare module.exports: $Exports<'html-loader/dist/plugins'>;
}
declare module 'html-loader/dist/plugins/index.js' {
  declare module.exports: $Exports<'html-loader/dist/plugins'>;
}
declare module 'html-loader/dist/plugins/minimizer-plugin.js' {
  declare module.exports: $Exports<'html-loader/dist/plugins/minimizer-plugin'>;
}
declare module 'html-loader/dist/plugins/source-plugin.js' {
  declare module.exports: $Exports<'html-loader/dist/plugins/source-plugin'>;
}
declare module 'html-loader/dist/runtime/getUrl.js' {
  declare module.exports: $Exports<'html-loader/dist/runtime/getUrl'>;
}
declare module 'html-loader/dist/utils.js' {
  declare module.exports: $Exports<'html-loader/dist/utils'>;
}
