// flow-typed signature: 10d5103f19eed52ea4612e8237e29c4d
// flow-typed version: <<STUB>>/koa-compress_v3.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-compress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-compress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-compress/index' {
  declare module.exports: $Exports<'koa-compress'>;
}
declare module 'koa-compress/index.js' {
  declare module.exports: $Exports<'koa-compress'>;
}
