// flow-typed signature: 4c39a756f2a25c763dee33d21ef012e8
// flow-typed version: <<STUB>>/koa-logger_v3.2.1/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-logger/index' {
  declare module.exports: $Exports<'koa-logger'>;
}
declare module 'koa-logger/index.js' {
  declare module.exports: $Exports<'koa-logger'>;
}
