// flow-typed signature: c60881fe4362ce5d1c00386283eb3b5d
// flow-typed version: <<STUB>>/koa-webpack_v5.2.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack/lib/client' {
  declare module.exports: any;
}

declare module 'koa-webpack/lib/index' {
  declare module.exports: any;
}

declare module 'koa-webpack/lib/middleware' {
  declare module.exports: any;
}

declare module 'koa-webpack/lib/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack/lib/client.js' {
  declare module.exports: $Exports<'koa-webpack/lib/client'>;
}
declare module 'koa-webpack/lib/index.js' {
  declare module.exports: $Exports<'koa-webpack/lib/index'>;
}
declare module 'koa-webpack/lib/middleware.js' {
  declare module.exports: $Exports<'koa-webpack/lib/middleware'>;
}
declare module 'koa-webpack/lib/validate.js' {
  declare module.exports: $Exports<'koa-webpack/lib/validate'>;
}
