// flow-typed signature: 92f6ca27d7816bf12bd66ebdee1cd6fe
// flow-typed version: <<STUB>>/neutrino-preset-flow_v0.0.4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino-preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino-preset-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'neutrino-preset-flow/index' {
  declare module.exports: $Exports<'neutrino-preset-flow'>;
}
declare module 'neutrino-preset-flow/index.js' {
  declare module.exports: $Exports<'neutrino-preset-flow'>;
}
