// flow-typed signature: 2a2764bd21c94bb50d9a3a9805f9aca2
// flow-typed version: <<STUB>>/neutrino_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neutrino/bin/base' {
  declare module.exports: any;
}

declare module 'neutrino/bin/build' {
  declare module.exports: any;
}

declare module 'neutrino/bin/execute' {
  declare module.exports: any;
}

declare module 'neutrino/bin/inspect' {
  declare module.exports: any;
}

declare module 'neutrino/bin/neutrino' {
  declare module.exports: any;
}

declare module 'neutrino/bin/start' {
  declare module.exports: any;
}

declare module 'neutrino/bin/test' {
  declare module.exports: any;
}

declare module 'neutrino/src/api' {
  declare module.exports: any;
}

declare module 'neutrino/src/build' {
  declare module.exports: any;
}

declare module 'neutrino/src/devServer' {
  declare module.exports: any;
}

declare module 'neutrino/src/index' {
  declare module.exports: any;
}

declare module 'neutrino/src/inspect' {
  declare module.exports: any;
}

declare module 'neutrino/src/start' {
  declare module.exports: any;
}

declare module 'neutrino/src/test' {
  declare module.exports: any;
}

declare module 'neutrino/src/utils' {
  declare module.exports: any;
}

declare module 'neutrino/src/watch' {
  declare module.exports: any;
}

declare module 'neutrino/src/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neutrino/bin/base.js' {
  declare module.exports: $Exports<'neutrino/bin/base'>;
}
declare module 'neutrino/bin/build.js' {
  declare module.exports: $Exports<'neutrino/bin/build'>;
}
declare module 'neutrino/bin/execute.js' {
  declare module.exports: $Exports<'neutrino/bin/execute'>;
}
declare module 'neutrino/bin/inspect.js' {
  declare module.exports: $Exports<'neutrino/bin/inspect'>;
}
declare module 'neutrino/bin/neutrino.js' {
  declare module.exports: $Exports<'neutrino/bin/neutrino'>;
}
declare module 'neutrino/bin/start.js' {
  declare module.exports: $Exports<'neutrino/bin/start'>;
}
declare module 'neutrino/bin/test.js' {
  declare module.exports: $Exports<'neutrino/bin/test'>;
}
declare module 'neutrino/src/api.js' {
  declare module.exports: $Exports<'neutrino/src/api'>;
}
declare module 'neutrino/src/build.js' {
  declare module.exports: $Exports<'neutrino/src/build'>;
}
declare module 'neutrino/src/devServer.js' {
  declare module.exports: $Exports<'neutrino/src/devServer'>;
}
declare module 'neutrino/src/index.js' {
  declare module.exports: $Exports<'neutrino/src/index'>;
}
declare module 'neutrino/src/inspect.js' {
  declare module.exports: $Exports<'neutrino/src/inspect'>;
}
declare module 'neutrino/src/start.js' {
  declare module.exports: $Exports<'neutrino/src/start'>;
}
declare module 'neutrino/src/test.js' {
  declare module.exports: $Exports<'neutrino/src/test'>;
}
declare module 'neutrino/src/utils.js' {
  declare module.exports: $Exports<'neutrino/src/utils'>;
}
declare module 'neutrino/src/watch.js' {
  declare module.exports: $Exports<'neutrino/src/watch'>;
}
declare module 'neutrino/src/webpack.js' {
  declare module.exports: $Exports<'neutrino/src/webpack'>;
}
