// flow-typed signature: a0c5be75c3b50460847cb8366bffacfc
// flow-typed version: <<STUB>>/neutrino-preset-koa_v1.0.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino-preset-koa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino-preset-koa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neutrino-preset-koa/src/get-ips' {
  declare module.exports: any;
}

declare module 'neutrino-preset-koa/src/index' {
  declare module.exports: any;
}

declare module 'neutrino-preset-koa/src/ip' {
  declare module.exports: any;
}

declare module 'neutrino-preset-koa/src/launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neutrino-preset-koa/src/get-ips.js' {
  declare module.exports: $Exports<'neutrino-preset-koa/src/get-ips'>;
}
declare module 'neutrino-preset-koa/src/index.js' {
  declare module.exports: $Exports<'neutrino-preset-koa/src/index'>;
}
declare module 'neutrino-preset-koa/src/ip.js' {
  declare module.exports: $Exports<'neutrino-preset-koa/src/ip'>;
}
declare module 'neutrino-preset-koa/src/launcher.js' {
  declare module.exports: $Exports<'neutrino-preset-koa/src/launcher'>;
}
