// flow-typed signature: 8040802bd84119f8f0c7ce723d976871
// flow-typed version: <<STUB>>/react-snapshot_v^1.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-snapshot/bin/react-snapshot' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/cli' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/Crawler' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/index' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/Server' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/snapshot' {
  declare module.exports: any;
}

declare module 'react-snapshot/lib/Writer' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/cli' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/Crawler' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/index' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/Server' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/snapshot' {
  declare module.exports: any;
}

declare module 'react-snapshot/src/Writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-snapshot/bin/react-snapshot.js' {
  declare module.exports: $Exports<'react-snapshot/bin/react-snapshot'>;
}
declare module 'react-snapshot/lib/cli.js' {
  declare module.exports: $Exports<'react-snapshot/lib/cli'>;
}
declare module 'react-snapshot/lib/Crawler.js' {
  declare module.exports: $Exports<'react-snapshot/lib/Crawler'>;
}
declare module 'react-snapshot/lib/index.js' {
  declare module.exports: $Exports<'react-snapshot/lib/index'>;
}
declare module 'react-snapshot/lib/Server.js' {
  declare module.exports: $Exports<'react-snapshot/lib/Server'>;
}
declare module 'react-snapshot/lib/snapshot.js' {
  declare module.exports: $Exports<'react-snapshot/lib/snapshot'>;
}
declare module 'react-snapshot/lib/Writer.js' {
  declare module.exports: $Exports<'react-snapshot/lib/Writer'>;
}
declare module 'react-snapshot/src/cli.js' {
  declare module.exports: $Exports<'react-snapshot/src/cli'>;
}
declare module 'react-snapshot/src/Crawler.js' {
  declare module.exports: $Exports<'react-snapshot/src/Crawler'>;
}
declare module 'react-snapshot/src/index.js' {
  declare module.exports: $Exports<'react-snapshot/src/index'>;
}
declare module 'react-snapshot/src/Server.js' {
  declare module.exports: $Exports<'react-snapshot/src/Server'>;
}
declare module 'react-snapshot/src/snapshot.js' {
  declare module.exports: $Exports<'react-snapshot/src/snapshot'>;
}
declare module 'react-snapshot/src/Writer.js' {
  declare module.exports: $Exports<'react-snapshot/src/Writer'>;
}
