// flow-typed signature: eb2a2849bbf9ef3919390d8029ffb25a
// flow-typed version: <<STUB>>/react-snap_v1.23.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-snap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-snap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-snap/run' {
  declare module.exports: any;
}

declare module 'react-snap/src/puppeteer_utils' {
  declare module.exports: any;
}

declare module 'react-snap/src/tracker' {
  declare module.exports: any;
}

declare module 'react-snap/vendor/preload_polyfill.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-snap/index' {
  declare module.exports: $Exports<'react-snap'>;
}
declare module 'react-snap/index.js' {
  declare module.exports: $Exports<'react-snap'>;
}
declare module 'react-snap/run.js' {
  declare module.exports: $Exports<'react-snap/run'>;
}
declare module 'react-snap/src/puppeteer_utils.js' {
  declare module.exports: $Exports<'react-snap/src/puppeteer_utils'>;
}
declare module 'react-snap/src/tracker.js' {
  declare module.exports: $Exports<'react-snap/src/tracker'>;
}
declare module 'react-snap/vendor/preload_polyfill.min.js' {
  declare module.exports: $Exports<'react-snap/vendor/preload_polyfill.min'>;
}
