// flow-typed signature: 7239e04b3482dc1e1d24ec2751cf415e
// flow-typed version: <<STUB>>/react-helmet_v6.1.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet/es/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/Helmet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet/es/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/es/Helmet'>;
}
declare module 'react-helmet/lib/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/lib/Helmet'>;
}
