// flow-typed signature: bbb7f048437632670c3066a9ebccb2d4
// flow-typed version: <<STUB>>/supertest_v3.4.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supertest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supertest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'supertest/lib/agent' {
  declare module.exports: any;
}

declare module 'supertest/lib/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'supertest/index' {
  declare module.exports: $Exports<'supertest'>;
}
declare module 'supertest/index.js' {
  declare module.exports: $Exports<'supertest'>;
}
declare module 'supertest/lib/agent.js' {
  declare module.exports: $Exports<'supertest/lib/agent'>;
}
declare module 'supertest/lib/test.js' {
  declare module.exports: $Exports<'supertest/lib/test'>;
}
