// flow-typed signature: 4259009ff614fc864db121a7722d1bef
// flow-typed version: <<STUB>>/terser-webpack-plugin_v4.2.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terser-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist/minify' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist/Webpack4Cache' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist/Webpack5Cache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terser-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/cjs'>;
}
declare module 'terser-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist'>;
}
declare module 'terser-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist'>;
}
declare module 'terser-webpack-plugin/dist/minify.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/minify'>;
}
declare module 'terser-webpack-plugin/dist/Webpack4Cache.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/Webpack4Cache'>;
}
declare module 'terser-webpack-plugin/dist/Webpack5Cache.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/Webpack5Cache'>;
}
