// flow-typed signature: d2546511495adf5e76924f9ec8c1fd66
// flow-typed version: <<STUB>>/terser_v5.3.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terser/dist/bundle.min' {
  declare module.exports: any;
}

declare module 'terser/lib/ast' {
  declare module.exports: any;
}

declare module 'terser/lib/cli' {
  declare module.exports: any;
}

declare module 'terser/lib/compress' {
  declare module.exports: any;
}

declare module 'terser/lib/equivalent-to' {
  declare module.exports: any;
}

declare module 'terser/lib/minify' {
  declare module.exports: any;
}

declare module 'terser/lib/mozilla-ast' {
  declare module.exports: any;
}

declare module 'terser/lib/output' {
  declare module.exports: any;
}

declare module 'terser/lib/parse' {
  declare module.exports: any;
}

declare module 'terser/lib/propmangle' {
  declare module.exports: any;
}

declare module 'terser/lib/scope' {
  declare module.exports: any;
}

declare module 'terser/lib/size' {
  declare module.exports: any;
}

declare module 'terser/lib/sourcemap' {
  declare module.exports: any;
}

declare module 'terser/lib/transform' {
  declare module.exports: any;
}

declare module 'terser/lib/utils/first_in_statement' {
  declare module.exports: any;
}

declare module 'terser/lib/utils' {
  declare module.exports: any;
}

declare module 'terser/main' {
  declare module.exports: any;
}

declare module 'terser/tools/domprops' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terser/dist/bundle.min.js' {
  declare module.exports: $Exports<'terser/dist/bundle.min'>;
}
declare module 'terser/lib/ast.js' {
  declare module.exports: $Exports<'terser/lib/ast'>;
}
declare module 'terser/lib/cli.js' {
  declare module.exports: $Exports<'terser/lib/cli'>;
}
declare module 'terser/lib/compress/index' {
  declare module.exports: $Exports<'terser/lib/compress'>;
}
declare module 'terser/lib/compress/index.js' {
  declare module.exports: $Exports<'terser/lib/compress'>;
}
declare module 'terser/lib/equivalent-to.js' {
  declare module.exports: $Exports<'terser/lib/equivalent-to'>;
}
declare module 'terser/lib/minify.js' {
  declare module.exports: $Exports<'terser/lib/minify'>;
}
declare module 'terser/lib/mozilla-ast.js' {
  declare module.exports: $Exports<'terser/lib/mozilla-ast'>;
}
declare module 'terser/lib/output.js' {
  declare module.exports: $Exports<'terser/lib/output'>;
}
declare module 'terser/lib/parse.js' {
  declare module.exports: $Exports<'terser/lib/parse'>;
}
declare module 'terser/lib/propmangle.js' {
  declare module.exports: $Exports<'terser/lib/propmangle'>;
}
declare module 'terser/lib/scope.js' {
  declare module.exports: $Exports<'terser/lib/scope'>;
}
declare module 'terser/lib/size.js' {
  declare module.exports: $Exports<'terser/lib/size'>;
}
declare module 'terser/lib/sourcemap.js' {
  declare module.exports: $Exports<'terser/lib/sourcemap'>;
}
declare module 'terser/lib/transform.js' {
  declare module.exports: $Exports<'terser/lib/transform'>;
}
declare module 'terser/lib/utils/first_in_statement.js' {
  declare module.exports: $Exports<'terser/lib/utils/first_in_statement'>;
}
declare module 'terser/lib/utils/index' {
  declare module.exports: $Exports<'terser/lib/utils'>;
}
declare module 'terser/lib/utils/index.js' {
  declare module.exports: $Exports<'terser/lib/utils'>;
}
declare module 'terser/main.js' {
  declare module.exports: $Exports<'terser/main'>;
}
declare module 'terser/tools/domprops.js' {
  declare module.exports: $Exports<'terser/tools/domprops'>;
}
