// flow-typed signature: 39134b23a676d4df4b727bfbbbc8f005
// flow-typed version: <<STUB>>/@babel/plugin-proposal-decorators_v7.10.5/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-decorators/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-decorators/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib'>;
}
declare module '@babel/plugin-proposal-decorators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib'>;
}
declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/transformer-legacy'>;
}
