// flow-typed signature: 52a88209805723d59a7c82d58e0d09ff
// flow-typed version: <<STUB>>/@neutrinojs/airbnb_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/airbnb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/airbnb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/airbnb/index' {
  declare module.exports: $Exports<'@neutrinojs/airbnb'>;
}
declare module '@neutrinojs/airbnb/index.js' {
  declare module.exports: $Exports<'@neutrinojs/airbnb'>;
}
