// flow-typed signature: 0b9c210e62374a6a84d10d06a0f9223b
// flow-typed version: <<STUB>>/@neutrinojs/env_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/env/index' {
  declare module.exports: $Exports<'@neutrinojs/env'>;
}
declare module '@neutrinojs/env/index.js' {
  declare module.exports: $Exports<'@neutrinojs/env'>;
}
