// flow-typed signature: b7280e0ed6632f6d8351c27175dc0f2c
// flow-typed version: <<STUB>>/@neutrinojs/eslint_v^8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/eslint/index' {
  declare module.exports: $Exports<'@neutrinojs/eslint'>;
}
declare module '@neutrinojs/eslint/index.js' {
  declare module.exports: $Exports<'@neutrinojs/eslint'>;
}
