// flow-typed signature: 7b005dd548ae1219c2ba1b566500e8bf
// flow-typed version: <<STUB>>/@neutrinojs/fork_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/fork'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/fork' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@neutrinojs/fork/neutrino-child' {
  declare module.exports: any;
}

// Filename aliases
declare module '@neutrinojs/fork/index' {
  declare module.exports: $Exports<'@neutrinojs/fork'>;
}
declare module '@neutrinojs/fork/index.js' {
  declare module.exports: $Exports<'@neutrinojs/fork'>;
}
declare module '@neutrinojs/fork/neutrino-child.js' {
  declare module.exports: $Exports<'@neutrinojs/fork/neutrino-child'>;
}
