// flow-typed signature: f09bda6aaebbb2efd513bb3d90581ac4
// flow-typed version: <<STUB>>/@neutrinojs/jest_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@neutrinojs/jest/src/file-mock' {
  declare module.exports: any;
}

declare module '@neutrinojs/jest/src/index' {
  declare module.exports: any;
}

declare module '@neutrinojs/jest/src/style-mock' {
  declare module.exports: any;
}

declare module '@neutrinojs/jest/src/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@neutrinojs/jest/src/file-mock.js' {
  declare module.exports: $Exports<'@neutrinojs/jest/src/file-mock'>;
}
declare module '@neutrinojs/jest/src/index.js' {
  declare module.exports: $Exports<'@neutrinojs/jest/src/index'>;
}
declare module '@neutrinojs/jest/src/style-mock.js' {
  declare module.exports: $Exports<'@neutrinojs/jest/src/style-mock'>;
}
declare module '@neutrinojs/jest/src/transformer.js' {
  declare module.exports: $Exports<'@neutrinojs/jest/src/transformer'>;
}
