// flow-typed signature: 4f594e7281e8c33663eb11f48a131412
// flow-typed version: <<STUB>>/@neutrinojs/node_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/node/index' {
  declare module.exports: $Exports<'@neutrinojs/node'>;
}
declare module '@neutrinojs/node/index.js' {
  declare module.exports: $Exports<'@neutrinojs/node'>;
}
