// flow-typed signature: 5812dd459683ee8b3d3ae31e92885922
// flow-typed version: <<STUB>>/@neutrinojs/react_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/react/index' {
  declare module.exports: $Exports<'@neutrinojs/react'>;
}
declare module '@neutrinojs/react/index.js' {
  declare module.exports: $Exports<'@neutrinojs/react'>;
}
