// flow-typed signature: 45f616d5e2d4e17a77b4ab77b3ffb1ca
// flow-typed version: <<STUB>>/@neutrinojs/style-loader_v8.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/style-loader/index' {
  declare module.exports: $Exports<'@neutrinojs/style-loader'>;
}
declare module '@neutrinojs/style-loader/index.js' {
  declare module.exports: $Exports<'@neutrinojs/style-loader'>;
}
